site_name: My Docs
site_url: https://elieahd.github.io/my-docs/
site_author: Elie Daher

repo_name: elieahd/my-docs
repo_url: https://github.com/elieahd/my-docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins: 
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc

nav:
- Home: index.md
- Tech:
  - Tips: 
    - 01 - Debugging a Java Stream in IntelliJ: tech/tips/java-stream-intellij.md
    - 02 - JSON processing with jq: tech/tips/jq.md
    - 03 - API conventions: tech/tips/api-conventions.md
    - 04 - My most used K8S commands: tech/tips/k8s-commands.md
    - 05 - Text processing with awk: tech/tips/awk.md
    - 06 - Searching through files with grep: tech/tips/grep.md
    - 07 - Transform and replace text in files with sed: tech/tips/sed.md
    - 08 - Making HTTP requests with curl: tech/tips/curl.md
    - 09 - Resilience testing with chaos engineering: tech/tips/chaos.md
