site_name: My Docs
site_url: https://github.com/pages/elieahd/my-docs
site_author: Elie Daher

repo_name: elieahd/my-docs
repo_url: https://github.com/elieahd/my-docs

theme:
  name: material

plugins: 
  - search
  - minify
  - navincluder

nav:
- Home: "index.md"
- Tech: "@include tech/nav.yml"
