site_name: My Docs
site_url: https://elieahd.github.io/my-docs/
site_author: Elie Daher

repo_name: elieahd/my-docs
repo_url: https://github.com/elieahd/my-docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins: 
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

nav:
- Home: "index.md"
- Tech:
  - Tips: 
    - Debugging a Java Stream in IntelliJ: tech/tips/java-stream-intellij.md
    - JSON processing in shell with jq: tech/tips/jq.md
    - My most used K8S commands: tech/tips/k8s-commands.md
    - API conventions: tech/tips/api-conventions.md
