site_name: My Docs
site_url: https://elieahd.github.io/my-docs/
site_author: Elie Daher

repo_name: elieahd/my-docs
repo_url: https://github.com/elieahd/my-docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins: 
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc

nav:
- Home: index.md
- Tech: 
  - Backend:
    - Debugging a Java Stream in IntelliJ: tech/backend/java-stream-intellij.md 
    - API guidelines: tech/backend/api-guidelines.md
    - Structure unit tests: tech/backend/aaa.md
    - Resilience testing with chaos engineering: tech/backend/chaos.md
  - Devops: 
    - My most used K8S commands: tech/devops/kubectl.md
  - Shell:
    - JSON processing with jq: tech/shell/jq.md
    - Text processing with awk: tech/shell/awk.md
    - Searching through files with grep: tech/shell/grep.md
    - Transform and replace text in files with sed: tech/shell/sed.md
    - Making HTTP requests with curl: tech/shell/curl.md
