site_name: My Docs
site_url: https://elieahd.github.io/my-docs/
site_author: Elie Daher

repo_name: elieahd/my-docs
repo_url: https://github.com/elieahd/my-docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins: 
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc

nav:
- Home: index.md
- Tech: 
  - Backend:
    - API guidelines: tech/backend/api-guidelines.md
    - Structure unit tests: tech/backend/aaa.md
    - Debugging a Java Stream in IntelliJ: tech/backend/java-stream-intellij.md 
  - Devops: 
    - My most used K8S commands: tech/devops/kubectl.md
  - Shell:
    - Text editing with sed: tech/shell/sed.md
    - Text searching with grep: tech/shell/grep.md
    - Text processing with awk: tech/shell/awk.md
    - Making HTTP requests with curl: tech/shell/curl.md
    - JSON processing with jq: tech/shell/jq.md
  - Tech debt: tech/tech-debt.md
- Architecture: 
  - TOGAF:
    - Foundation:
      - 1. Introduction and Concepts: architecture/togaf/foundation/unit1.md
      - 2. Definitions: architecture/togaf/foundation/unit2.md
      - 3. Introduction to the ADM Phases: architecture/togaf/foundation/unit3.md
      - 4. Introduction to ADM Techniques: architecture/togaf/foundation/unit4.md
      - 5. Introduction to Applying the ADM: architecture/togaf/foundation/unit5.md
      - 6. Introduction to Architecture Governance: notes/togaf/foundation/unit6.md
      - 7. Architecture Content: architecture/togaf/foundation/unit7.md
